// Pure rendering fixtures: no app, network, recorded user data, or model calls.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '../static/jobs.js'), 'utf8');
const escape = source.match(/function escapeHtml\(s\) \{[\s\S]*?\n\}/)[0];
const helper = source.slice(source.indexOf('function toolResultsHtml(r) {'), source.indexOf('function resultHtml(jobId, r) {'));
const ctx = vm.createContext({openEvidence: new Set()});
vm.runInContext(escape + '\n' + helper, ctx);
const render = row => ctx.toolResultsHtml(row);
assert.equal(render({}), '');
assert.equal(render({tool_results: []}), '');
const malicious = '<img src=x onerror="window.pwned=1"><script>alert(1)</script>&';
const html = render({id: malicious, tool_results: [{name: malicious, output: malicious, ok: false, error_type: malicious}]});
assert.ok(html.includes('조회 원문 · 1건'));
assert.ok(html.includes('실패'));
assert.ok(html.includes('&lt;img src=x onerror=&quot;window.pwned=1&quot;&gt;'));
assert.ok(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;&amp;'));
assert.ok(!html.includes('<img'));
assert.ok(!html.includes('<script'));
const raw = JSON.stringify({hits: [1, 2, 3].map(i => ({title: 'Fixture ' + i, url: 'https://example.invalid/post-' + i}))});
const evidence = render({tool_results: [{name: 'http__fixture', output: raw, ok: true, truncated: true}], tool_results_truncated: true, tool_results_omitted: 2});
assert.ok(evidence.includes('https://example.invalid/post-3'));
assert.ok(evidence.includes('&quot;hits&quot;'));
assert.ok(evidence.includes('<pre class="run-full">'));
assert.ok(evidence.includes('보관 한도로 일부 출력이 생략'));
assert.ok(evidence.includes('기록하지 못한 도구 실행 2건'));
assert.ok(!evidence.includes('<a '));
assert.ok(!evidence.includes('<iframe'));
ctx.openEvidence.add('fixture-run');
assert.ok(render({id: 'fixture-run', tool_results: [{name: 'fixture', output: 'raw', ok: true}]}).includes('data-evidence="fixture-run" open'));
console.log('Tool evidence rendering passed: raw JSON, escaped untrusted text, legacy rows, and truncation.');
